<a href="https://colab.research.google.com/github/brijeshpal/Deep-Learning/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install --upgrade pip setuptools wheel


In [ ]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

In [ ]:
## One Hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[34, 164, 374, 377], [34, 164, 374, 125], [34, 107, 374, 46], [425, 177, 281, 254, 255], [425, 177, 281, 254, 38], [104, 34, 321, 374, 486], [460, 181, 181, 254]]


Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## Pre= Added zero first
## Post= Added zero last
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  34 164 374 377]
 [  0   0   0   0  34 164 374 125]
 [  0   0   0   0  34 107 374  46]
 [  0   0   0 425 177 281 254 255]
 [  0   0   0 425 177 281 254  38]
 [  0   0   0 104  34 321 374 486]
 [  0   0   0   0 460 181 181 254]]


In [ ]:
## 10 feature dimesnions ## In this each and every value converted into vectors
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  34, 164, 374, 377], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step


array([[ 6.9108829e-03, -3.0350232e-02, -3.7174333e-02, -3.3978306e-02,
         1.9196812e-02, -1.2431383e-02,  3.2327548e-03, -4.6631850e-02,
         1.0671131e-03,  2.7593706e-02],
       [ 6.9108829e-03, -3.0350232e-02, -3.7174333e-02, -3.3978306e-02,
         1.9196812e-02, -1.2431383e-02,  3.2327548e-03, -4.6631850e-02,
         1.0671131e-03,  2.7593706e-02],
       [ 6.9108829e-03, -3.0350232e-02, -3.7174333e-02, -3.3978306e-02,
         1.9196812e-02, -1.2431383e-02,  3.2327548e-03, -4.6631850e-02,
         1.0671131e-03,  2.7593706e-02],
       [ 6.9108829e-03, -3.0350232e-02, -3.7174333e-02, -3.3978306e-02,
         1.9196812e-02, -1.2431383e-02,  3.2327548e-03, -4.6631850e-02,
         1.0671131e-03,  2.7593706e-02],
       [ 6.8545341e-05, -6.7873821e-03,  8.9764819e-03, -2.5924504e-02,
         1.2557317e-02,  3.4780908e-02, -4.8681870e-03,  2.5122907e-02,
        -2.3847187e-02, -1.7353453e-02],
       [ 4.6970252e-02, -4.0196050e-02,  4.8563067e-02, -1.9742139e-03,
   

In [ ]:
print(embedded_docs.shape)


(7, 8)


In [ ]:
embedded_docs = embedded_docs.astype('int32')


In [ ]:
print(model.predict(embedded_docs))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None